from __future__ import annotations

from dataclasses import dataclass

from app.privacy.data_inventory import (
    PrivacyFieldClassification,
    PrivacyFieldErasureAction,
)


@dataclass(frozen=True, slots=True)
class PrivacyColumnPolicy:
    """Column-level DSR handling contract for an inventoried table column."""

    table_name: str
    column_name: str
    classification: PrivacyFieldClassification
    export: bool
    erasure_action: PrivacyFieldErasureAction
    rationale: str


def _policy(
    table_name: str,
    column_name: str,
    classification: PrivacyFieldClassification,
    export: bool,
    erasure_action: PrivacyFieldErasureAction,
    rationale: str,
) -> PrivacyColumnPolicy:
    return PrivacyColumnPolicy(
        table_name=table_name,
        column_name=column_name,
        classification=classification,
        export=export,
        erasure_action=erasure_action,
        rationale=rationale,
    )


CLASS_INDIRECT = PrivacyFieldClassification.INDIRECT_IDENTIFIER
CLASS_DIRECT = PrivacyFieldClassification.DIRECT_IDENTIFIER
CLASS_CONTACT = PrivacyFieldClassification.CONTACT_POINT
CLASS_SECRET = PrivacyFieldClassification.SECRET_OR_TOKEN
CLASS_REASON = PrivacyFieldClassification.OPERATIONAL_REASON
CLASS_NETWORK = PrivacyFieldClassification.NETWORK_IDENTIFIER
CLASS_USER_AGENT = PrivacyFieldClassification.USER_AGENT
CLASS_RELATIONSHIP = PrivacyFieldClassification.RELATIONSHIP
CLASS_LIFECYCLE = PrivacyFieldClassification.LIFECYCLE
CLASS_METADATA = PrivacyFieldClassification.STRUCTURED_METADATA

ACTION_ANONYMISE = PrivacyFieldErasureAction.ANONYMISE
ACTION_DELETE = PrivacyFieldErasureAction.DELETE
ACTION_RETAIN = PrivacyFieldErasureAction.RETAIN
ACTION_MINIMISE = PrivacyFieldErasureAction.RETAIN_MINIMISED
ACTION_REMOVE_PAYLOAD = PrivacyFieldErasureAction.REMOVE_PAYLOAD_VALUE
ACTION_REVIEW = PrivacyFieldErasureAction.REVIEW_REQUIRED


PRIVACY_COLUMN_POLICIES: tuple[PrivacyColumnPolicy, ...] = (
    # users
    _policy(
        "users",
        "id",
        CLASS_INDIRECT,
        True,
        ACTION_MINIMISE,
        "Primary key needed for references.",
    ),
    _policy(
        "users",
        "created_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Account creation timestamp.",
    ),
    _policy(
        "users",
        "updated_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Account update timestamp.",
    ),
    _policy(
        "users",
        "external_auth_id",
        CLASS_DIRECT,
        True,
        ACTION_ANONYMISE,
        "External IdP identifier.",
    ),
    _policy(
        "users",
        "email",
        CLASS_CONTACT,
        True,
        ACTION_ANONYMISE,
        "Primary account contact point.",
    ),
    _policy(
        "users",
        "email_verified",
        CLASS_METADATA,
        True,
        ACTION_RETAIN,
        "Email verification state.",
    ),
    _policy(
        "users",
        "first_name",
        CLASS_DIRECT,
        True,
        ACTION_ANONYMISE,
        "Profile direct identifier.",
    ),
    _policy(
        "users",
        "last_name",
        CLASS_DIRECT,
        True,
        ACTION_ANONYMISE,
        "Profile direct identifier.",
    ),
    _policy(
        "users",
        "onboarding_completed",
        CLASS_METADATA,
        True,
        ACTION_RETAIN,
        "Product state.",
    ),
    _policy(
        "users",
        "status",
        CLASS_LIFECYCLE,
        True,
        ACTION_MINIMISE,
        "Account lifecycle state.",
    ),
    _policy(
        "users",
        "suspended_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Suspension timestamp.",
    ),
    _policy(
        "users",
        "suspended_reason",
        CLASS_REASON,
        True,
        ACTION_REVIEW,
        "Operational reason text.",
    ),
    # memberships
    _policy(
        "memberships",
        "id",
        CLASS_INDIRECT,
        True,
        ACTION_MINIMISE,
        "Membership record key.",
    ),
    _policy(
        "memberships",
        "created_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Membership creation time.",
    ),
    _policy(
        "memberships",
        "updated_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Membership update time.",
    ),
    _policy(
        "memberships",
        "user_id",
        CLASS_INDIRECT,
        True,
        ACTION_MINIMISE,
        "Subject user link.",
    ),
    _policy(
        "memberships",
        "organisation_id",
        CLASS_RELATIONSHIP,
        True,
        ACTION_MINIMISE,
        "Tenant relationship.",
    ),
    _policy(
        "memberships",
        "role",
        CLASS_RELATIONSHIP,
        True,
        ACTION_MINIMISE,
        "Assigned tenant role.",
    ),
    _policy(
        "memberships",
        "is_active",
        CLASS_LIFECYCLE,
        True,
        ACTION_MINIMISE,
        "Membership lifecycle flag.",
    ),
    # organisations
    _policy(
        "organisations",
        "id",
        CLASS_INDIRECT,
        True,
        ACTION_RETAIN,
        "Tenant record key.",
    ),
    _policy(
        "organisations",
        "created_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Tenant creation time.",
    ),
    _policy(
        "organisations",
        "updated_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Tenant update time.",
    ),
    _policy(
        "organisations",
        "name",
        CLASS_METADATA,
        True,
        ACTION_RETAIN,
        "Tenant display name.",
    ),
    _policy(
        "organisations",
        "slug",
        CLASS_METADATA,
        True,
        ACTION_RETAIN,
        "Tenant slug.",
    ),
    _policy(
        "organisations",
        "deleted_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Soft-delete timestamp.",
    ),
    _policy(
        "organisations",
        "status",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Tenant lifecycle state.",
    ),
    _policy(
        "organisations",
        "suspended_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Suspension timestamp.",
    ),
    _policy(
        "organisations",
        "suspended_reason",
        CLASS_REASON,
        True,
        ACTION_REVIEW,
        "Operational reason text.",
    ),
    # invites
    _policy(
        "invites",
        "id",
        CLASS_INDIRECT,
        True,
        ACTION_MINIMISE,
        "Invite record key.",
    ),
    _policy(
        "invites",
        "created_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Invite creation time.",
    ),
    _policy(
        "invites",
        "updated_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Invite update time.",
    ),
    _policy(
        "invites",
        "email",
        CLASS_CONTACT,
        True,
        ACTION_ANONYMISE,
        "Invitee contact point.",
    ),
    _policy(
        "invites",
        "organisation_id",
        CLASS_RELATIONSHIP,
        True,
        ACTION_MINIMISE,
        "Inviting tenant link.",
    ),
    _policy(
        "invites",
        "role",
        CLASS_RELATIONSHIP,
        True,
        ACTION_MINIMISE,
        "Invited tenant role.",
    ),
    _policy(
        "invites",
        "status",
        CLASS_LIFECYCLE,
        True,
        ACTION_MINIMISE,
        "Invite lifecycle state.",
    ),
    _policy(
        "invites",
        "token_hash",
        CLASS_SECRET,
        False,
        ACTION_DELETE,
        "Invite token hash.",
    ),
    _policy(
        "invites",
        "expires_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Invite expiry time.",
    ),
    _policy(
        "invites",
        "revoked_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Invite revocation time.",
    ),
    _policy(
        "invites",
        "revoked_by_user_id",
        CLASS_INDIRECT,
        True,
        ACTION_MINIMISE,
        "Revoker user link.",
    ),
    # outbox_events
    _policy(
        "outbox_events",
        "id",
        CLASS_INDIRECT,
        True,
        ACTION_MINIMISE,
        "Outbox record key.",
    ),
    _policy(
        "outbox_events",
        "created_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Outbox creation time.",
    ),
    _policy(
        "outbox_events",
        "updated_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Outbox update time.",
    ),
    _policy(
        "outbox_events",
        "event_type",
        CLASS_METADATA,
        True,
        ACTION_RETAIN,
        "Event type metadata.",
    ),
    _policy(
        "outbox_events",
        "aggregate_type",
        CLASS_METADATA,
        True,
        ACTION_RETAIN,
        "Aggregate type metadata.",
    ),
    _policy(
        "outbox_events",
        "aggregate_id",
        CLASS_INDIRECT,
        True,
        ACTION_MINIMISE,
        "Aggregate identifier.",
    ),
    _policy(
        "outbox_events",
        "payload_json",
        CLASS_METADATA,
        False,
        ACTION_REMOVE_PAYLOAD,
        "Payload can contain PII.",
    ),
    _policy(
        "outbox_events",
        "status",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Delivery lifecycle state.",
    ),
    _policy(
        "outbox_events",
        "attempts",
        CLASS_METADATA,
        True,
        ACTION_RETAIN,
        "Delivery attempt count.",
    ),
    _policy(
        "outbox_events",
        "max_attempts",
        CLASS_METADATA,
        True,
        ACTION_RETAIN,
        "Delivery retry limit.",
    ),
    _policy(
        "outbox_events",
        "next_attempt_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Next retry timestamp.",
    ),
    _policy(
        "outbox_events",
        "locked_at",
        CLASS_LIFECYCLE,
        False,
        ACTION_RETAIN,
        "Worker lock timestamp.",
    ),
    _policy(
        "outbox_events",
        "processed_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Delivery completion time.",
    ),
    _policy(
        "outbox_events",
        "last_error",
        CLASS_REASON,
        False,
        ACTION_REVIEW,
        "Delivery error text.",
    ),
    # audit_events
    _policy(
        "audit_events",
        "id",
        CLASS_INDIRECT,
        True,
        ACTION_MINIMISE,
        "Audit record key.",
    ),
    _policy(
        "audit_events",
        "actor_user_id",
        CLASS_INDIRECT,
        True,
        ACTION_MINIMISE,
        "Actor user link.",
    ),
    _policy(
        "audit_events",
        "category",
        CLASS_METADATA,
        True,
        ACTION_RETAIN,
        "Audit category.",
    ),
    _policy(
        "audit_events",
        "action",
        CLASS_METADATA,
        True,
        ACTION_RETAIN,
        "Audit action.",
    ),
    _policy(
        "audit_events",
        "target_type",
        CLASS_METADATA,
        True,
        ACTION_MINIMISE,
        "Target discriminator.",
    ),
    _policy(
        "audit_events",
        "target_id",
        CLASS_INDIRECT,
        True,
        ACTION_MINIMISE,
        "Target identifier.",
    ),
    _policy(
        "audit_events",
        "reason",
        CLASS_REASON,
        True,
        ACTION_REVIEW,
        "Operational reason text.",
    ),
    _policy(
        "audit_events",
        "metadata_json",
        CLASS_METADATA,
        True,
        ACTION_REVIEW,
        "Allowlisted metadata only.",
    ),
    _policy(
        "audit_events",
        "ip_address",
        CLASS_NETWORK,
        True,
        ACTION_MINIMISE,
        "Network identifier.",
    ),
    _policy(
        "audit_events",
        "user_agent",
        CLASS_USER_AGENT,
        True,
        ACTION_MINIMISE,
        "Browser fingerprint risk.",
    ),
    _policy(
        "audit_events",
        "legal_hold_until",
        CLASS_LIFECYCLE,
        False,
        ACTION_RETAIN,
        "Internal legal hold.",
    ),
    _policy(
        "audit_events",
        "created_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Audit event timestamp.",
    ),
    # platform_staff
    _policy(
        "platform_staff",
        "id",
        CLASS_INDIRECT,
        True,
        ACTION_MINIMISE,
        "Staff record key.",
    ),
    _policy(
        "platform_staff",
        "created_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Staff grant time.",
    ),
    _policy(
        "platform_staff",
        "updated_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Staff record update time.",
    ),
    _policy(
        "platform_staff",
        "user_id",
        CLASS_INDIRECT,
        True,
        ACTION_MINIMISE,
        "Staff user link.",
    ),
    _policy(
        "platform_staff",
        "role",
        CLASS_RELATIONSHIP,
        True,
        ACTION_MINIMISE,
        "Platform role.",
    ),
    _policy(
        "platform_staff",
        "status",
        CLASS_LIFECYCLE,
        True,
        ACTION_MINIMISE,
        "Staff lifecycle state.",
    ),
    _policy(
        "platform_staff",
        "created_by_user_id",
        CLASS_INDIRECT,
        True,
        ACTION_MINIMISE,
        "Granting actor link.",
    ),
    _policy(
        "platform_staff",
        "suspended_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Suspension timestamp.",
    ),
    _policy(
        "platform_staff",
        "suspended_reason",
        CLASS_REASON,
        True,
        ACTION_REVIEW,
        "Operational reason text.",
    ),
    # data_subject_requests
    _policy(
        "data_subject_requests",
        "id",
        CLASS_INDIRECT,
        True,
        ACTION_MINIMISE,
        "DSR record key.",
    ),
    _policy(
        "data_subject_requests",
        "created_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "DSR creation time.",
    ),
    _policy(
        "data_subject_requests",
        "updated_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "DSR update time.",
    ),
    _policy(
        "data_subject_requests",
        "request_type",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "DSR type.",
    ),
    _policy(
        "data_subject_requests",
        "status",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "DSR status.",
    ),
    _policy(
        "data_subject_requests",
        "execution_status",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "DSR execution state.",
    ),
    _policy(
        "data_subject_requests",
        "execution_started_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Execution start time.",
    ),
    _policy(
        "data_subject_requests",
        "execution_completed_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Execution completion time.",
    ),
    _policy(
        "data_subject_requests",
        "execution_failed_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Execution failure time.",
    ),
    _policy(
        "data_subject_requests",
        "execution_failure_reason_code",
        CLASS_REASON,
        True,
        ACTION_MINIMISE,
        "Structured execution failure reason.",
    ),
    _policy(
        "data_subject_requests",
        "execution_failure_detail",
        CLASS_REASON,
        False,
        ACTION_REVIEW,
        "Internal execution failure detail.",
    ),
    _policy(
        "data_subject_requests",
        "requester_user_id",
        CLASS_INDIRECT,
        True,
        ACTION_MINIMISE,
        "Requester link.",
    ),
    _policy(
        "data_subject_requests",
        "subject_user_id",
        CLASS_INDIRECT,
        True,
        ACTION_MINIMISE,
        "Subject link.",
    ),
    _policy(
        "data_subject_requests",
        "reviewer_user_id",
        CLASS_INDIRECT,
        True,
        ACTION_MINIMISE,
        "Reviewer link.",
    ),
    _policy(
        "data_subject_requests",
        "submitted_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Submission time.",
    ),
    _policy(
        "data_subject_requests",
        "acknowledged_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Acknowledgement time.",
    ),
    _policy(
        "data_subject_requests",
        "reviewed_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Review time.",
    ),
    _policy(
        "data_subject_requests",
        "decided_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Decision time.",
    ),
    _policy(
        "data_subject_requests",
        "fulfilled_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Fulfilment time.",
    ),
    _policy(
        "data_subject_requests",
        "cancelled_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Cancellation time.",
    ),
    _policy(
        "data_subject_requests",
        "decision_reason_code",
        CLASS_REASON,
        True,
        ACTION_MINIMISE,
        "Decision reason.",
    ),
    _policy(
        "data_subject_requests",
        "rejection_reason_code",
        CLASS_REASON,
        True,
        ACTION_MINIMISE,
        "Rejection reason.",
    ),
    _policy(
        "data_subject_requests",
        "requester_note",
        CLASS_REASON,
        True,
        ACTION_REVIEW,
        "Requester note.",
    ),
    _policy(
        "data_subject_requests",
        "internal_note",
        CLASS_REASON,
        False,
        ACTION_REVIEW,
        "Internal note.",
    ),
    _policy(
        "data_subject_requests",
        "due_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Response deadline.",
    ),
    _policy(
        "data_subject_requests",
        "extended_until",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Extended deadline.",
    ),
    _policy(
        "data_subject_requests",
        "extension_reason_code",
        CLASS_REASON,
        True,
        ACTION_MINIMISE,
        "Extension reason.",
    ),
    _policy(
        "data_subject_requests",
        "idempotency_key_hash",
        CLASS_SECRET,
        False,
        ACTION_DELETE,
        "Idempotency hash.",
    ),
    _policy(
        "data_subject_requests",
        "idempotency_fingerprint",
        CLASS_SECRET,
        False,
        ACTION_DELETE,
        "Request fingerprint.",
    ),
    _policy(
        "data_subject_requests",
        "idempotency_key_expires_at",
        CLASS_LIFECYCLE,
        False,
        ACTION_DELETE,
        "Idempotency expiry.",
    ),
    _policy(
        "data_subject_requests",
        "export_artifact_id",
        CLASS_RELATIONSHIP,
        True,
        ACTION_MINIMISE,
        "Export artifact link.",
    ),
    _policy(
        "data_subject_requests",
        "erasure_job_id",
        CLASS_RELATIONSHIP,
        True,
        ACTION_MINIMISE,
        "Future erasure job link.",
    ),
    # export_artifacts
    _policy(
        "export_artifacts",
        "id",
        CLASS_INDIRECT,
        True,
        ACTION_MINIMISE,
        "Artifact record key.",
    ),
    _policy(
        "export_artifacts",
        "created_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Artifact creation time.",
    ),
    _policy(
        "export_artifacts",
        "updated_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Artifact update time.",
    ),
    _policy(
        "export_artifacts",
        "data_subject_request_id",
        CLASS_RELATIONSHIP,
        True,
        ACTION_MINIMISE,
        "Parent DSR link.",
    ),
    _policy(
        "export_artifacts",
        "subject_user_id",
        CLASS_INDIRECT,
        True,
        ACTION_MINIMISE,
        "Subject link.",
    ),
    _policy(
        "export_artifacts",
        "requester_user_id",
        CLASS_INDIRECT,
        True,
        ACTION_MINIMISE,
        "Requester link.",
    ),
    _policy(
        "export_artifacts",
        "status",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Artifact lifecycle state.",
    ),
    _policy(
        "export_artifacts",
        "format",
        CLASS_METADATA,
        True,
        ACTION_RETAIN,
        "Artifact format.",
    ),
    _policy(
        "export_artifacts",
        "storage_backend",
        CLASS_METADATA,
        False,
        ACTION_RETAIN,
        "Storage backend detail.",
    ),
    _policy(
        "export_artifacts",
        "storage_key",
        CLASS_INDIRECT,
        False,
        ACTION_DELETE,
        "Storage locator.",
    ),
    _policy(
        "export_artifacts",
        "filename",
        CLASS_METADATA,
        True,
        ACTION_MINIMISE,
        "Download filename.",
    ),
    _policy(
        "export_artifacts",
        "content_type",
        CLASS_METADATA,
        True,
        ACTION_RETAIN,
        "MIME type.",
    ),
    _policy(
        "export_artifacts",
        "size_bytes",
        CLASS_METADATA,
        True,
        ACTION_RETAIN,
        "Object size.",
    ),
    _policy(
        "export_artifacts",
        "checksum_sha256",
        CLASS_METADATA,
        True,
        ACTION_MINIMISE,
        "Integrity hash.",
    ),
    _policy(
        "export_artifacts",
        "schema_version",
        CLASS_METADATA,
        True,
        ACTION_RETAIN,
        "Export schema version.",
    ),
    _policy(
        "export_artifacts",
        "requested_by_user_id",
        CLASS_INDIRECT,
        True,
        ACTION_MINIMISE,
        "Requesting actor link.",
    ),
    _policy(
        "export_artifacts",
        "generated_by_user_id",
        CLASS_INDIRECT,
        True,
        ACTION_MINIMISE,
        "Generating actor link.",
    ),
    _policy(
        "export_artifacts",
        "failure_reason_code",
        CLASS_REASON,
        True,
        ACTION_MINIMISE,
        "Failure reason.",
    ),
    _policy(
        "export_artifacts",
        "failure_detail",
        CLASS_REASON,
        False,
        ACTION_REVIEW,
        "Internal failure detail.",
    ),
    _policy(
        "export_artifacts",
        "queued_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Queue timestamp.",
    ),
    _policy(
        "export_artifacts",
        "started_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Processing start time.",
    ),
    _policy(
        "export_artifacts",
        "processing_token",
        CLASS_SECRET,
        False,
        ACTION_DELETE,
        "Worker lease token.",
    ),
    _policy(
        "export_artifacts",
        "processing_lease_expires_at",
        CLASS_LIFECYCLE,
        False,
        ACTION_DELETE,
        "Lease expiry.",
    ),
    _policy(
        "export_artifacts",
        "completed_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Processing completion time.",
    ),
    _policy(
        "export_artifacts",
        "failed_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Processing failure time.",
    ),
    _policy(
        "export_artifacts",
        "expires_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Artifact expiry time.",
    ),
    _policy(
        "export_artifacts",
        "download_url_issued_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Last download URL issuance time.",
    ),
    _policy(
        "export_artifacts",
        "download_url_issue_count",
        CLASS_METADATA,
        True,
        ACTION_RETAIN,
        "Download URL issuance count.",
    ),
    _policy(
        "export_artifacts",
        "downloaded_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_MINIMISE,
        "Confirmed delivery time.",
    ),
    _policy(
        "export_artifacts",
        "download_count",
        CLASS_METADATA,
        True,
        ACTION_MINIMISE,
        "Confirmed delivery count.",
    ),
    # data_processing_authorizations
    _policy(
        "data_processing_authorizations",
        "id",
        CLASS_INDIRECT,
        True,
        ACTION_MINIMISE,
        "Authorization key.",
    ),
    _policy(
        "data_processing_authorizations",
        "created_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Creation time.",
    ),
    _policy(
        "data_processing_authorizations",
        "updated_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Update time.",
    ),
    _policy(
        "data_processing_authorizations",
        "subject_user_id",
        CLASS_INDIRECT,
        True,
        ACTION_MINIMISE,
        "Subject link.",
    ),
    _policy(
        "data_processing_authorizations",
        "purpose_id",
        CLASS_RELATIONSHIP,
        True,
        ACTION_MINIMISE,
        "Purpose link.",
    ),
    _policy(
        "data_processing_authorizations",
        "lawful_basis",
        CLASS_METADATA,
        True,
        ACTION_RETAIN,
        "Lawful basis.",
    ),
    _policy(
        "data_processing_authorizations",
        "special_category_condition",
        CLASS_METADATA,
        True,
        ACTION_RETAIN,
        "Special-category condition.",
    ),
    _policy(
        "data_processing_authorizations",
        "active",
        CLASS_METADATA,
        True,
        ACTION_RETAIN,
        "Authorization state.",
    ),
    _policy(
        "data_processing_authorizations",
        "valid_from",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Validity start.",
    ),
    _policy(
        "data_processing_authorizations",
        "valid_until",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Validity end.",
    ),
    _policy(
        "data_processing_authorizations",
        "revoked_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Revocation time.",
    ),
    _policy(
        "data_processing_authorizations",
        "source",
        CLASS_METADATA,
        True,
        ACTION_REVIEW,
        "Authorization source.",
    ),
    # consent_records
    _policy(
        "consent_records",
        "id",
        CLASS_INDIRECT,
        True,
        ACTION_MINIMISE,
        "Consent record key.",
    ),
    _policy(
        "consent_records",
        "created_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Creation time.",
    ),
    _policy(
        "consent_records",
        "updated_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Update time.",
    ),
    _policy(
        "consent_records",
        "subject_user_id",
        CLASS_INDIRECT,
        True,
        ACTION_MINIMISE,
        "Subject link.",
    ),
    _policy(
        "consent_records",
        "purpose_id",
        CLASS_RELATIONSHIP,
        True,
        ACTION_MINIMISE,
        "Purpose link.",
    ),
    _policy(
        "consent_records",
        "authorization_id",
        CLASS_RELATIONSHIP,
        True,
        ACTION_MINIMISE,
        "Authorization link.",
    ),
    _policy(
        "consent_records",
        "privacy_notice_version",
        CLASS_METADATA,
        True,
        ACTION_RETAIN,
        "Notice version.",
    ),
    _policy(
        "consent_records",
        "granted_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Consent grant time.",
    ),
    _policy(
        "consent_records",
        "withdrawn_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Withdrawal time.",
    ),
    _policy(
        "consent_records",
        "withdrawal_reason_code",
        CLASS_REASON,
        True,
        ACTION_REVIEW,
        "Withdrawal reason.",
    ),
    # privacy_notice_acceptances
    _policy(
        "privacy_notice_acceptances",
        "id",
        CLASS_INDIRECT,
        True,
        ACTION_MINIMISE,
        "Acceptance key.",
    ),
    _policy(
        "privacy_notice_acceptances",
        "created_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Creation time.",
    ),
    _policy(
        "privacy_notice_acceptances",
        "updated_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Update time.",
    ),
    _policy(
        "privacy_notice_acceptances",
        "subject_user_id",
        CLASS_INDIRECT,
        True,
        ACTION_MINIMISE,
        "Subject link.",
    ),
    _policy(
        "privacy_notice_acceptances",
        "notice_version",
        CLASS_METADATA,
        True,
        ACTION_RETAIN,
        "Notice version.",
    ),
    _policy(
        "privacy_notice_acceptances",
        "accepted_at",
        CLASS_LIFECYCLE,
        True,
        ACTION_RETAIN,
        "Acceptance time.",
    ),
    _policy(
        "privacy_notice_acceptances",
        "source",
        CLASS_METADATA,
        True,
        ACTION_REVIEW,
        "Acceptance source.",
    ),
)


def get_privacy_column_policies_by_table() -> dict[str, dict[str, PrivacyColumnPolicy]]:
    grouped: dict[str, dict[str, PrivacyColumnPolicy]] = {}
    for policy in PRIVACY_COLUMN_POLICIES:
        table = grouped.setdefault(policy.table_name, {})
        if policy.column_name in table:
            raise ValueError(
                "Duplicate privacy column policy for "
                f"{policy.table_name}.{policy.column_name}"
            )
        table[policy.column_name] = policy
    return grouped


def get_privacy_column_policy(table_name: str, column_name: str) -> PrivacyColumnPolicy:
    return get_privacy_column_policies_by_table()[table_name][column_name]
