from __future__ import annotations

from opentelemetry import metrics

meter = metrics.get_meter("fastapi_saas_template")

# Backward-compatible re-exports for existing imports.
from app.core.observability.http_metrics import (  # noqa: E402
    ALLOWED_HTTP_ATTRIBUTE_KEYS,
    ALLOWED_HTTP_ERROR_ATTRIBUTE_KEYS,
    HTTP_ATTRIBUTE_METHOD,
    HTTP_ATTRIBUTE_ROUTE,
    HTTP_ATTRIBUTE_STATUS_CODE,
    HTTP_ERRORS_TOTAL,
    HTTP_REQUEST_DURATION,
    HTTP_REQUESTS_TOTAL,
    record_http_error,
    record_http_request,
    record_http_request_duration,
)
from app.core.observability.rate_limit_metrics import (  # noqa: E402
    ALLOWED_RATE_LIMIT_ATTRIBUTE_KEYS,
    ALLOWED_RATE_LIMIT_RESULTS,
    RATE_LIMIT_ATTRIBUTE_ERROR_TYPE,
    RATE_LIMIT_ATTRIBUTE_IDENTIFIER_KIND,
    RATE_LIMIT_ATTRIBUTE_POLICY,
    RATE_LIMIT_ATTRIBUTE_RESULT,
    RATE_LIMIT_RESULT_ALLOWED,
    RATE_LIMIT_RESULT_BACKEND_ERROR,
    RATE_LIMIT_RESULT_BLOCKED,
    RATE_LIMIT_RESULT_FAIL_OPEN,
    RATE_LIMIT_RESULT_RUNTIME_UNAVAILABLE,
    rate_limit_backend_errors_total,
    rate_limit_check_duration,
    rate_limit_requests_total,
    record_rate_limit_backend_error,
    record_rate_limit_check_duration,
    record_rate_limit_decision,
)
from app.core.observability.route import get_route_template  # noqa: E402
from app.core.observability.safety import (  # noqa: E402
    OBSERVABILITY_RECORDING_FAILURES_TOTAL_NAME,
    _handle_metric_recording_failure,
    _last_metrics_failure_log_at,
    _log_metrics_failure,
    _monotonic,
    _record_observability_failure_metric,
    _safe_record_metric,
    observability_recording_failures_total,
)

__all__ = [
    "meter",
    "ALLOWED_HTTP_ATTRIBUTE_KEYS",
    "ALLOWED_HTTP_ERROR_ATTRIBUTE_KEYS",
    "ALLOWED_RATE_LIMIT_ATTRIBUTE_KEYS",
    "ALLOWED_RATE_LIMIT_RESULTS",
    "HTTP_ATTRIBUTE_METHOD",
    "HTTP_ATTRIBUTE_ROUTE",
    "HTTP_ATTRIBUTE_STATUS_CODE",
    "HTTP_ERRORS_TOTAL",
    "HTTP_REQUEST_DURATION",
    "HTTP_REQUESTS_TOTAL",
    "OBSERVABILITY_RECORDING_FAILURES_TOTAL_NAME",
    "RATE_LIMIT_ATTRIBUTE_ERROR_TYPE",
    "RATE_LIMIT_ATTRIBUTE_IDENTIFIER_KIND",
    "RATE_LIMIT_ATTRIBUTE_POLICY",
    "RATE_LIMIT_ATTRIBUTE_RESULT",
    "RATE_LIMIT_RESULT_ALLOWED",
    "RATE_LIMIT_RESULT_BACKEND_ERROR",
    "RATE_LIMIT_RESULT_BLOCKED",
    "RATE_LIMIT_RESULT_FAIL_OPEN",
    "RATE_LIMIT_RESULT_RUNTIME_UNAVAILABLE",
    "_handle_metric_recording_failure",
    "_last_metrics_failure_log_at",
    "_log_metrics_failure",
    "_monotonic",
    "_record_observability_failure_metric",
    "_safe_record_metric",
    "get_route_template",
    "observability_recording_failures_total",
    "rate_limit_backend_errors_total",
    "rate_limit_check_duration",
    "rate_limit_requests_total",
    "record_http_error",
    "record_http_request",
    "record_http_request_duration",
    "record_rate_limit_backend_error",
    "record_rate_limit_check_duration",
    "record_rate_limit_decision",
]
